version: '3'
services:
  mysql-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5506:5506"
    networks:
      - kalash-network
  server-container:
    build:
      context: .
      dockerfile: dockerfile
    image: kalashsql
    ports:
      - "5000:5000"
    networks:
      - kalash-network
    depends_on:
      - mysql-server

networks:
  kalash-network:
    driver: bridge